### PR TITLE
Expose gcd, lcm, and gcdext functions on BAP bitvectors

### PR DESCRIPTION
**Pull request by DIJamner**
Adds the functions `gcd`, `lcm`, and `gcdext` to the bitvector interface. `gcd` computes the greatest common denominator of the inputs, `lcm` computes the least common multiple, and `gcdext` also computes coefficients `s` and `t` such that if `gcdext x y = (d, s, t)` then `d = s*x + t*y`.

Also adds functions `gcd_exn`, `lcm_exn`, and `gcdext_exn` that raise exceptions on improper inputs rather than returning an error.

### CODE REVIEW

**Comment by ivg** [comment]
We have some failures in [the tests][1]:
```
Error: BAP:1:Bitvector:95:lcm.
File "/home/travis/build/BinaryAnalysisPlatform/bap/oUnit-BAP-travis-job-dc56087e-d72e-406d-a199-93a759c7c30d#01.log", line 428, characters 1-1:
Error: BAP:1:Bitvector:95:lcm (in the log).
Raised at file "src/oUnitAssert.ml", line 45, characters 2-27
Called from file "src/oUnitRunner.ml", line 46, characters 13-26
expected: 0x23:8u but got: 0x8C:8u
------------------------------------------------------------------------------
==============================================================================
Error: BAP:1:Bitvector:94:lcm.
File "/home/travis/build/BinaryAnalysisPlatform/bap/oUnit-BAP-travis-job-dc56087e-d72e-406d-a199-93a759c7c30d#01.log", line 419, characters 1-1:
Error: BAP:1:Bitvector:94:lcm (in the log).
Raised at file "src/oUnitAssert.ml", line 45, characters 2-27
Called from file "src/oUnitRunner.ml", line 46, characters 13-26
expected: 0x18:8u but got: 0x30:8u
------------------------------------------------------------------------------
Ran: 3555 tests in: 264.70 seconds.
FAILED: Cases: 3555 Tried: 3555 Errors: 0 Failures: 2 Skip:  0 Todo: 0 Timeouts: 0.
```

[1]: https://travis-ci.org/BinaryAnalysisPlatform/bap/jobs/353039231#L795

**Comment by ivg** [comment]
To run tests on your local machine you need to pass `--enable-tests` to the `./configure` script (besides other options) and run `make test` .

**Comment by DIJamner** [comment]
Thanks for letting me know, I'm looking at it now. I'd thought it was running the tests and my code has been working well with this PR. I'll make sure to fix it up.

**Comment by DIJamner** [comment]
Tests have been fixed. I just put in the wrong expected values for the lcm tests. I verified the expected results against another implementation of lcm to make sure I calculated correctly.

**Pull request merged**
