### PR TITLE
Add space before output from --system-libs

### PR DESCRIPTION
**Pull request by maverickwoo**
Fix building with LLVM 3.8

Ensure a space between the outputs of `llvm-config --ldflags` and `llvm-config --system-libs`.

### CODE REVIEW

**Comment by ivg** [comment]
He, also working for llvm-3.8 support on macports. Unfortunately having few issues there. By the way, on what system under which configuration the absence of the space triggered a problem?

**Comment by maverickwoo** [comment]
I am also on MacPorts. Actual delimited outputs from my system to show why the space is needed:
```
$ echo ^$(llvm-config-mp-3.8 --ldflags)^
^-L/opt/local/libexec/llvm-3.8/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names^

$ echo ^$(llvm-config-mp-3.8 --system-libs)^
^-lcurses -lpthread -lz -lm^
```

**Comment by ivg** [comment]
What bugs me, is that it works on Xenial, so I'm wondering what is specific to macports, that triggers the problem. 

Also, is it OK of I will postpone the merge until I have time to test it on Xenial. (Travis tests only on Precise)

**Comment by maverickwoo** [comment]
The reason it works on xenial is because there is a trailing space in the output for `llvm-config --ldflags`. But of course we cannot count on this extra space:
```
ubuntu@ubuntu-xenial:~$ echo ^$(llvm-config --ldflags)^
^-L/usr/lib/llvm-3.8/lib ^
ubuntu@ubuntu-xenial:~$ echo ^$(llvm-config --system-libs)^
^-lrt -ldl -ltinfo -lpthread -lz -lm^
```
Waiting is perfectly OK with me. :)

**Comment by ivg** [comment]
fyi, I've tested it on xenial it works fine.

**Comment by maverickwoo** [comment]
Ouch. I committed to the wrong branch. :) The last two travis changes are supposed to be on a different branch---I didn't mean to touch this PR. I guess I know what my next 4 git steps are. Let's see...

**Comment by ivg** [comment]
just `git reset --hard HEAD~2` and `git push origin fix-llvm-ldflags` (but make sure that you're on a correct branch before doing the `hard` reset!

**Comment by maverickwoo** [comment]
Alright, done. Just let me know if you want me to rebase to latest master. I didn't know GitHub can detect that two of my commits have vanished. :)

**Comment by ivg** [comment]
You don't need to rebase, but just hit the update button, it will merge with the master.

**Pull request merged**
