### PR TITLE
Updating to LLVM 3.5

### PR DESCRIPTION
**Pull request by perror**
Here is a patch that compiles and seems to work (but need further testing...).

### CODE REVIEW

**Comment by ivg** [comment]
Great! 
But now the interesting part, we can't just get rid of old LLVM 3.4, so we need to support both.

**Comment by perror** [comment]
Well, I was sure you would ask for more. :-)
I may look at it later on, but feel free to use these few lines if you are quicker than I am !

**Comment by ivg** [comment]
Thanks! At least you've showed that it is doable. We will address this issue later. Currently there is also a big PR pending, that will add more LLVM dependency.

**Comment by ivg** [comment]
we will return to it soon. Thanks!

**Comment by perror** [comment]
Augh, I was battling with OCaml OASIS to get it right, but I have the proper C++ file (if it might help you):

    diff --git a/lib/bap_disasm/llvm_disasm.cpp b/lib/bap_disasm/llvm_disasm.cpp
    index 2927df2..720bb23 100644
    --- a/lib/bap_disasm/llvm_disasm.cpp
    +++ b/lib/bap_disasm/llvm_disasm.cpp
    @@ -1,4 +1,6 @@
    -#include <llvm/ADT/OwningPtr.h>
    +#if LLVM_VERSION_MAJOR == 3 && LLVM_VERSION_MINOR < 5
    +  #include <llvm/ADT/OwningPtr.h>
    +#endif
     #include <llvm/MC/MCAsmInfo.h>
     #include <llvm/MC/MCContext.h>
     #include <llvm/MC/MCDisassembler.h>
    @@ -176,9 +178,13 @@ public:
                 return {nullptr, bap_disasm_unsupported_target};
             }
 

    +#if LLVM_VERSION_MAJOR == 3 && LLVM_VERSION_MINOR < 5
    	llvm::OwningPtr<llvm::MCRelocationInfo>
    +            rel_info(target->createMCRelocationInfo(triple, *ctx));
    +#else
    +        std::unique_ptr<llvm::MCRelocationInfo>
                 rel_info(target->createMCRelocationInfo(triple, *ctx));
    +#endif
 
             if (!rel_info) {
                 if (debug_level > 0)
    @@ -186,13 +192,23 @@ public:
                 return {nullptr, bap_disasm_unsupported_target};
             }
 
    +#if LLVM_VERSION_MAJOR == 3 && LLVM_VERSION_MINOR < 5
    	llvm::OwningPtr<llvm::MCSymbolizer>
                 symbolizer(target->createMCSymbolizer(
                                triple,
                                nullptr, // getOpInfo
                                nullptr, // SymbolLookUp
                                nullptr, // DisInfo
                                &*ctx, rel_info.take()));
    +#else
    +        std::unique_ptr<llvm::MCSymbolizer>
    +            symbolizer(target->createMCSymbolizer(
    +                           triple,
    +                           nullptr, // getOpInfo
    +                           nullptr, // SymbolLookUp
    +                           nullptr, // DisInfo
    +                           &*ctx, rel_info.release()));
    +#endif
 
             if (!symbolizer) {
                 if (debug_level > 0)
    @@ -213,8 +229,13 @@ public:
             /* Make the default for immediates to be in hex */
             printer->setPrintImmHex(true);
 
    +#if LLVM_VERSION_MAJOR == 3 && LLVM_VERSION_MINOR < 5
    +        shared_ptr<llvm::MCDisassembler>
    +	  dis(target->createMCDisassembler(*sub_info));
    +#else
             shared_ptr<llvm::MCDisassembler>
    -            dis(target->createMCDisassembler(*sub_info));
    +	        dis(target->createMCDisassembler(*sub_info, *ctx));
    +#endif
 
             if (!dis) {
                 if (debug_level > 0)
    @@ -222,12 +243,16 @@ public:
                 return {nullptr, bap_disasm_unsupported_target};
             }
 
    +#if LLVM_VERSION_MAJOR == 3 && LLVM_VERSION_MINOR < 5
     	dis->setSymbolizer(symbolizer);
     	dis->setupForSymbolicDisassembly(
                 nullptr, // getOpInfo
                 nullptr, // SymbolLookUp
                 nullptr, // DisInfo,
                 &*ctx, rel_info);
    +#else
    +	dis->setSymbolizer(std::move(symbolizer));
    +#endif
 
             shared_ptr<llvm_disassembler> self(new llvm_disassembler(debug_level));
             self->printer  = printer;

**Comment by ivg** [comment]
looks promising, thank you. Should I reopen the PR?

**Comment by perror** [comment]
No, I still need to handle the presence or not of the `llvm-config --system-libs` in the `setup.ml.in` file... So, I just need to battle a little more with OCaml (I need to practice more anyway!). I will do another PR when everything will be ready (except if you are quicker than me !).

**Pull request closed without merging**
